## Overview

### I have been given a dataset with recruits personality scores and the department that they applied for. 
### I will clean the data, and find insights from the data.

### import required packages

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Read in the dataset personality_scores.csv.

In [2]:
scores = pd.read_csv('personality_scores.csv', delimiter =';')

### Examine the data frame for duplicates and NaN values.

In [11]:
scores.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1555 entries, 0 to 1554
Data columns (total 70 columns):
ID                                                                          1555 non-null int64
Section 5 of 6 [I am always prepared.]                                      1555 non-null object
Section 5 of 6 [I am easily disturbed.]                                     1555 non-null object
Section 5 of 6 [I am exacting (demanding) in my work.]                      1555 non-null object
Section 5 of 6 [I am full of ideas.]                                        1555 non-null object
Section 5 of 6 [I am interested in people.]                                 1555 non-null object
Section 5 of 6 [I am not interested in abstract ideas.]                     1555 non-null object
Section 5 of 6 [I am not interested in other people's problems.]            1555 non-null object
Section 5 of 6 [I am not really interested in others.]                      1555 non-null object
Section 5 of 6 [I am quick to understand things.]                           1555 non-null object
Section 5 of 6 [I am quiet around strangers.]                               1555 non-null object
Section 5 of 6 [I am relaxed most of the time.]                             1555 non-null object
Section 5 of 6 [I am the life of the party.]                                1555 non-null object
Section 5 of 6 [I change my mood a lot.]                                    1555 non-null object
Section 5 of 6 [I do not have a good imagination.]                          1555 non-null object
Section 5 of 6 [I don't like to draw attention to myself.]                  1555 non-null object
Section 5 of 6 [I don't mind being the center of attention.]                1555 non-null object
Section 5 of 6 [I don't talk a lot.]                                        1555 non-null object
Section 5 of 6 [I feel comfortable around people.]                          1555 non-null object
Section 5 of 6 [I feel little concern for others.]                          1555 non-null object
Section 5 of 6 [I feel others' emotions.]                                   1555 non-null object
Section 5 of 6 [I follow a schedule.]                                       1555 non-null object
Section 5 of 6 [I get chores done right away.]                              1555 non-null object
Section 5 of 6 [I get irritated easily.]                                    1555 non-null object
Section 5 of 6 [I get stressed out easily.]                                 1555 non-null object
Section 5 of 6 [I get upset easily.]                                        1555 non-null object
Section 5 of 6 [I have a rich vocabulary.]                                  1555 non-null object
Section 5 of 6 [I have a soft (kind) heart.]                                1555 non-null object
Section 5 of 6 [I have a vivid imagination.]                                1555 non-null object
Section 5 of 6 [I have difficulty understanding abstract ideas.]            1555 non-null object
Section 5 of 6 [I have excellent ideas.]                                    1555 non-null object
Section 5 of 6 [I have frequent mood swings.]                               1555 non-null object
Section 5 of 6 [I have little to say.]                                      1555 non-null object
Section 5 of 6 [I insult people.]                                           1555 non-null object
Section 5 of 6 [I keep in the background.]                                  1555 non-null object
Section 5 of 6 [I leave my belongings lying around.]                        1555 non-null object
Section 5 of 6 [I like order.]                                              1555 non-null object
Section 5 of 6 [I make a mess of things.]                                   1555 non-null object
Section 5 of 6 [I make people feel at ease.]                                1555 non-null object
Section 5 of 6 [I neglect my duties.]                                       1555 non-null object
Section 5 of 6 [I often feel blue (down).]                                  1555 non-null object
Section 5 of 6 [I often forget to put things back in their proper place]    1555 non-null object
Section 5 of 6 [I pay attention to details.]                                1555 non-null object
Section 5 of 6 [I seldom feel blue (down).]                                 1555 non-null object
Section 5 of 6 [I spend time reflecting on things.]                         1555 non-null object
Section 5 of 6 [I start conversations.]                                     1555 non-null object
Section 5 of 6 [I sympathize with others' feelings.]                        1555 non-null object
Section 5 of 6 [I take time out for others.]                                1555 non-null object
Section 5 of 6 [I talk to a lot of different people at parties.]            1555 non-null object
Section 5 of 6 [I use difficult words.]                                     1555 non-null object
Section 5 of 6 [I worry about things.]                                      1555 non-null object
Unnamed: 51                                                                 0 non-null float64
Unnamed: 52                                                                 0 non-null float64
Unnamed: 53                                                                 0 non-null float64
Unnamed: 54                                                                 0 non-null float64
Unnamed: 55                                                                 0 non-null float64
Unnamed: 56                                                                 0 non-null float64
Unnamed: 57                                                                 0 non-null float64
Unnamed: 58                                                                 0 non-null float64
Unnamed: 59                                                                 0 non-null float64
Unnamed: 60                                                                 0 non-null float64
Unnamed: 61                                                                 0 non-null float64
Unnamed: 62                                                                 0 non-null float64
Unnamed: 63                                                                 0 non-null float64
Unnamed: 64                                                                 0 non-null float64
Unnamed: 65                                                                 0 non-null float64
Unnamed: 66                                                                 0 non-null float64
Unnamed: 67                                                                 0 non-null float64
Unnamed: 68                                                                 0 non-null float64
IPIP_HIGH_RISK                                                              0 non-null float64
dtypes: float64(19), int64(1), object(50)
memory usage: 546.7+ KB

In [9]:
scores.isna().sum().sum()

29545

### There aren't any duplicate columns but there are 29545 NaN values in the dataset. 
### I cannot use the columns with NaN values so I will drop them.

In [20]:
scores_clean = scores.dropna(axis = 1, how ='any')

In [21]:
scores_clean.isna().sum().sum()

0

In [22]:
scores_clean.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

### I have dropped all the NaN values and now I can work with the dataset
### I see that the index and ID columns are the same so I'm going to make the ID the index

In [23]:
scores_clean = scores_clean.set_index('ID')

In [24]:
scores_clean.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

### Write functions that will (1) convert the answer on each of the personality test questions to a number, as set out in scoring.md, and (2) calculate total scores for each of the subscales (conscientiousness, emotional stability, openness to new experience, agreeableness, extraversion).

In [25]:
def sum_per_subscale(scores_per_person, subscale):
    subscale_sum = sum([eval(scores_per_person[i])[1] for i in range(50) if eval(scores_per_person[i])[0] == subscale])
    return(subscale_sum)

sum_per_subscale(scores_clean.loc[0], 1)

scores_clean['Extraversion'] = scores_clean.apply(lambda row: sum_per_subscale(row, 1), axis=1)
scores_clean['Agreeableness'] = scores_clean.apply(lambda row: sum_per_subscale(row, 2), axis=1)
scores_clean['Conscientiousness'] = scores_clean.apply(lambda row: sum_per_subscale(row, 3), axis=1)
scores_clean['EmotionalStability'] = scores_clean.apply(lambda row: sum_per_subscale(row, 4), axis=1)
scores_clean['Intellect'] = scores_clean.apply(lambda row: sum_per_subscale(row, 5), axis=1)

### The function that I used above was worked on by nadja our mentor and us c13.

In [26]:
scores_clean.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,EmotionalStability,Intellect
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36

### Create a function/functions that takes in subscale total, and for each subscale, creates a new column called "{subscale_name}_interpretation" (e.g., conscientiousness_interpretation) and applies the labels "low", "medium", or "high" according to a person's score on that subscale. Cut-off scores corresponding to the low, medium and high groups can be found in scoring.md.

In [32]:
Extraversion_low = scores_clean['Extraversion'].mean() - scores_clean['Extraversion'].std()/2
Extraversion_high = scores_clean['Extraversion'].mean() + scores_clean['Extraversion'].std()/2

Agreeableness_low = scores_clean['Agreeableness'].mean() - scores_clean['Agreeableness'].std()/2
Agreeableness_high = scores_clean['Agreeableness'].mean() + scores_clean['Agreeableness'].std()/2

Conscientiousness_low = scores_clean['Conscientiousness'].mean() - scores_clean['Conscientiousness'].std()/2
Conscientiousness_high = scores_clean['Conscientiousness'].mean() + scores_clean['Conscientiousness'].std()/2

Emotional_Stability_low = scores_clean['EmotionalStability'].mean() - scores_clean['EmotionalStability'].std()/2
Emotional_Stability_high = scores_clean['EmotionalStability'].mean() + scores_clean['EmotionalStability'].std()/2

Intellect_low = scores_clean['Intellect'].mean() + scores_clean['Intellect'].std()/2
Intellect_high = scores_clean['Intellect'].mean() + scores_clean['Intellect'].std()/2

### Extraversion Low, Mediam and High

In [57]:
Extraversion_interpretation = []

for row in scores_clean['Extraversion']:
    if row < Extraversion_low:
        Extraversion_interpretation.append('Low')
    elif row > Extraversion_high:
        Extraversion_interpretation.append('High')
    else:
        Extraversion_interpretation.append('Medium')
        
scores_clean['Extraversion_interpretation'] = Extraversion_interpretation

### Conscientiousness Low, Mediam and high

In [56]:
Conscientiousness_interpretation = []

for row in scores_clean['Conscientiousness']:
    if row < Conscientiousness_low:
        Conscientiousness_interpretation.append('Low')
    elif row > Conscientiousness_high:
        Conscientiousness_interpretation.append('High')
    else:
        Conscientiousness_interpretation.append('Medium')
        
scores_clean['Conscientiousness_interpretation'] = Conscientiousness_interpretation

### Emotional_Stability Low, Mediam and high

In [55]:
Emotional_Stability_interpretation = []

for row in scores_clean['EmotionalStability']:
    if row < Emotional_Stability_low:
        Emotional_Stability_interpretation.append('Low')
    elif row > Emotional_Stability_high:
        Emotional_Stability_interpretation.append('High')
    else:
        Emotional_Stability_interpretation.append('Medium')
        
scores_clean['Emotional_Stability_interpretation'] = Emotional_Stability_interpretation

### Intellect Low, Medium and High

In [54]:
Intellect_interpretation = []

for row in scores_clean['Intellect']:
    if row < Intellect_low:
        Intellect_interpretation.append('Low')
    elif row > Intellect_high:
        Intellect_interpretation.append('High')
    else:
        Intellect_interpretation.append('Medium')
        
scores_clean['Intellect_interpretation'] = Intellect_interpretation

In [59]:
scores_clean.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,EmotionalStability,Intellect,Extraversion_interpretation,Conscientiousness_interpretation,Emotional_Stability_interpretation,Intellect_interpretation
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(4, 3)",30,40,48,36,42,Medium,High,Medium,Low
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(4, 3)",42,46,46,40,42,High,High,High,Low
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(4, 3)",28,40,40,38,42,Medium,Medium,Medium,Low
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(4, 1)",30,38,38,40,38,Medium,Low,High,Low
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(4, 3)",28,34,46,38,36,Medium,High,Medium,Low

### Read in the data in department_infromation.csv and merge this data frame with the personality score data frame, keeping all applicants within the department data frame. Assert that the newly created merged data frame has the same amount of rows as the department data frame, and the expected number of columns.

In [60]:
departments = pd.read_csv('departments.csv', delimiter = ';')

In [61]:
departments.head()

,ID,Department,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,IPIP_HIGH_RISK
0,0,Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### i want to find out how many NaN values there are

In [62]:
departments.isnull().sum().sum()

29545

### I have noticed that there are a number of rows with Null values. I am going to use .dropna(axis = 1, how ='any') to drop these columns because I cannot use them

In [63]:
departments = departments.dropna(axis = 1, how ='any')

In [64]:
departments.head()

   ID Department
0   0       Data
1   1       Data
2   2       Data
3   3       Data
4   4       Data

### I am going to make the index of the dataframe ID

In [65]:
departments = departments.set_index('ID')

In [66]:
departments.head()

   Department
ID
0        Data
1        Data
2        Data
3        Data
4        Data

### I will now join the two data sets

In [67]:
scores_join = scores_clean.join(departments)

In [68]:
scores_join.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Extraversion,Agreeableness,Conscientiousness,EmotionalStability,Intellect,Extraversion_interpretation,Conscientiousness_interpretation,Emotional_Stability_interpretation,Intellect_interpretation,Department
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,30,40,48,36,42,Medium,High,Medium,Low,Data
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,42,46,46,40,42,High,High,High,Low,Data
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,28,40,40,38,42,Medium,Medium,Medium,Low,Data
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,30,38,38,40,38,Medium,Low,High,Low,Data
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,28,34,46,38,36,Medium,High,Medium,Low,Data